FROM node:20-alpine as builder
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm ci

# Copy the rest of the backend code
COPY . .

# If using Prisma, generate the Prisma client
RUN npx prisma generate

FROM node:20-alpine as production
WORKDIR /app

# Copy all files from builder's /app into production /app
COPY --from=builder /app /app

ENV NODE_ENV=production
EXPOSE 4000

# Start the backend
CMD ["npm", "start"]
