version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_SUPABASE_URL: ${SUPABASE_URL}
        REACT_APP_SUPABASE_KEY: ${ANON_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_SUPABASE_URL: ${SUPABASE_URL}
      REACT_APP_SUPABASE_KEY: ${ANON_KEY}
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SUPABASE_AUTH_KEY: ${SERVICE_ROLE_KEY}
      SUPABASE_URL: ${SUPABASE_URL}
      ANON_KEY: ${ANON_KEY}
      JWT_SECRET: ${JWT_SECRET}
    # Remove or comment out the following lines:
    # volumes:
    #   - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
